### ISSUE TITLE
intersect_mesh_rays keyword name change is not backwards compatible

### ISSUE THREAD

**Issue by PH-Tools** [ladybug-tools/ladybug-rhino#230]
@chriswmackey, @mostaphaRoudsari 

Hi guys, I just noticed that the update to [ladybug_rhino/intersect.pyintersect_mesh_rays() L45](https://github.com/ladybug-tools/ladybug-rhino/blob/5d0a1a911113ba23c7e5706a84bc547743206f72/ladybug_rhino/intersect.py#L45) includes a change to the keyword arguments, ("parallel" -> "cpu_count"). 

This change makes sense, but is a breaking change for code that includes references to the previous keyword. What would you think about adding a handler for the older keyword and/or a deprecation warning? I'd be happy to try and add that and submit a PR, if you think it would be acceptable?

I would think I could either include a simple `**kwargs` argument to the function, and then a handler (`if kwargs.get('parallel')...`etc...) or if you don't like kwargs, I could alternatively just add that old keyword back in:

`def intersect_mesh_lines(mesh, start_points, end_points, max_dist=None, cpu_count=None, parallel=True):`

and then add a handler to the function body + a deprecation warning?
It's not a huge issue, but it definitely did cause some broken code after the update.

I'd be happy to give this a try, unless you think it would be a problem or you don't want this backwards compatibility for some reason.

thanks!
@PH-Tools

**Comment by chriswmackey** [comment]
Hey @PH-Tools ,

I am sorry that this broke your code and I had considered doing an implementation that still kept the `parallel` argument so as to not break certain uses of the SDK. I had decided against it because I wanted myself and everyone to switch over to the much better method of using the [recommended_processor_count](https://github.com/ladybug-tools/ladybug-rhino/blob/master/ladybug_rhino/grasshopper.py#L121-L130) by default. But I agree that the right way to do this was with a deprecation warning and I'm sorry about that.

If it's going to take you a while to implement the new method in your code, I can temporarily add the `parallel` option back, the default will be True and the only thing that it will do is override the `cpu_count` to 1 whenever it is set to False. Would this be ok?

FYI, this change was made in order to add support for [this update across the entire plugin](https://discourse.ladybug.tools/t/ladybug-tools-for-grasshopper-1-3-0-release/15783/2#general-improvements-for-parallel-processing-4). So that should give you a better sense of how you should edit your code to use the improved methods.

**Comment by PH-Tools** [comment]
Hi @chriswmackey , 
Not a problem: I already patched up all the code on our end to work with the new keyword argument, so no worries on that. I think we can easily enough provide a check / backwards-compatibility filter on our end for the components which are using that function, so I guess there is no need to add a bunch of extra code to the LBT functions unless you wanted to explicitly support backwards compatibility.
best,
@PH-Tools

**Comment by chriswmackey** [comment]
Thanks, @PH-Tools . I just decided to add it back after this PR:
https://github.com/ladybug-tools/ladybug-rhino/pull/233
I realized that it may be useful in the future to have an override to turn off parallelization.

I'm going to update the installer.gh on Food4Rhino later today to include this.
